language: node_js
node_js:
  - node
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
script:
  - npm install
    #  - if [[ $TRAVIS_NODE_VERSION == 0* ]]; then npm test; else npm run build; fi

